spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:postgres}?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false

app:
  pix:
    mock-enabled: false
  mercadopago:
    webhook-secret: ${MERCADOPAGO_WEBHOOK_SECRET}

logging:
  level:
    root: info
